

FLOOR_ = 50
WALL_ = 51
STONE_WALL_ = 52
DOOR_ = 53
STALAGTITE_ = 54
CRYSTAL_ = 55
SMALL_CRYSTAL_ = 56
EXIT_DOOR_ = 57
BRAZIER_ = 58

passable_terrain = {FLOOR_, DOOR_, CRYSTAL_, SMALL_CRYSTAL_, EXIT_DOOR_}
wall_terrains = {WALL_, STONE_WALL_}
vertical_wall_markers = {WALL_, STONE_WALL_, DOOR_}